"""initial schema

Revision ID: a400556d2783
Revises: 
Create Date: 2026-06-15 17:00:09.343867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a400556d2783'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_wording_versions',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('capture_method', sa.Enum('recorded', 'uploaded', name='capture_method'), nullable=False),
    sa.Column('language', sa.Enum('en', 'kh', name='language'), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('families',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_families_access_token'), 'families', ['access_token'], unique=True)
    op.create_index(op.f('ix_families_slug'), 'families', ['slug'], unique=True)
    op.create_table('chapters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('title_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_kh', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_family_id'), 'chapters', ['family_id'], unique=False)
    op.create_table('family_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_kh', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_deceased', sa.Boolean(), nullable=False),
    sa.Column('deceased_date', sa.Date(), nullable=True),
    sa.Column('deceased_date_precision', sa.Enum('year', 'month', 'day', name='deceased_date_precision'), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_members_family_id'), 'family_members', ['family_id'], unique=False)
    op.create_table('keepers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keepers_email'), 'keepers', ['email'], unique=True)
    op.create_index(op.f('ix_keepers_family_id'), 'keepers', ['family_id'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'processing', 'awaiting_review', 'rejected', 'in_review', 'published', 'archived', 'unpublished', 'deleted', name='story_status'), nullable=False),
    sa.Column('capture_method', sa.Enum('recorded', 'uploaded', name='capture_method'), nullable=False),
    sa.Column('narrator_id', sa.UUID(), nullable=True),
    sa.Column('narrator_name_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recorder_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consent_given_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consent_wording_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('language_detected', sa.Enum('kh', 'en', 'mixed', name='language_detected'), nullable=True),
    sa.Column('audio_quality_score', sa.Float(), nullable=True),
    sa.Column('translation_confidence_score', sa.Float(), nullable=True),
    sa.Column('translation_flagged', sa.Boolean(), nullable=False),
    sa.Column('processing_step', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('processing_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title_kh', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('chapter_id', sa.UUID(), nullable=True),
    sa.Column('chapter_sort_order', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['archived_by'], ['keepers.id'], ),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['consent_wording_key'], ['consent_wording_versions.key'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['narrator_id'], ['family_members.id'], ),
    sa.ForeignKeyConstraint(['published_by'], ['keepers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_family_id'), 'stories', ['family_id'], unique=False)
    op.create_table('ai_people_mentions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('name_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('family_member_id', sa.UUID(), nullable=True),
    sa.Column('resolution_status', sa.Enum('pending', 'linked', 'dismissed', name='mention_resolution_status'), nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['family_member_id'], ['family_members.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['keepers.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_people_mentions_story_id'), 'ai_people_mentions', ['story_id'], unique=False)
    op.create_table('audio_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('storage_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_type', sa.Enum('original', name='audio_file_type'), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_files_family_id'), 'audio_files', ['family_id'], unique=False)
    op.create_index(op.f('ix_audio_files_story_id'), 'audio_files', ['story_id'], unique=False)
    op.create_table('consent_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('narrator_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('capture_method', sa.Enum('recorded', 'uploaded', name='capture_method'), nullable=False),
    sa.Column('consent_wording_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_hint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pre_submission_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('story_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['consent_wording_key'], ['consent_wording_versions.key'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_log_family_id'), 'consent_log', ['family_id'], unique=False)
    op.create_index(op.f('ix_consent_log_story_id'), 'consent_log', ['story_id'], unique=False)
    op.create_table('deletion_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolution', sa.Enum('deleted', 'rejected', name='deletion_resolution'), nullable=True),
    sa.Column('resolution_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['keepers.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deletion_requests_family_id'), 'deletion_requests', ['family_id'], unique=False)
    op.create_index(op.f('ix_deletion_requests_story_id'), 'deletion_requests', ['story_id'], unique=False)
    op.create_table('keeper_locks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('keeper_id', sa.UUID(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['keeper_id'], ['keepers.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keeper_locks_story_id'), 'keeper_locks', ['story_id'], unique=True)
    op.create_table('story_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('family_member_id', sa.UUID(), nullable=True),
    sa.Column('name_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tagged_by', sa.Enum('recorder', 'keeper', name='tagged_by'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['family_member_id'], ['family_members.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_tags_story_id'), 'story_tags', ['story_id'], unique=False)
    op.create_table('title_suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.Enum('en', 'kh', name='language'), nullable=False),
    sa.Column('suggestion_index', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_title_suggestions_story_id'), 'title_suggestions', ['story_id'], unique=False)
    op.create_table('transcript_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.Enum('en', 'kh', name='language'), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('original_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('edited_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('edited_by', sa.UUID(), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('word_timestamps', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['edited_by'], ['keepers.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_segments_story_id'), 'transcript_segments', ['story_id'], unique=False)
    op.create_table('translation_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('transcript_segment_id', sa.UUID(), nullable=False),
    sa.Column('source_language', sa.Enum('en', 'kh', name='language'), nullable=False),
    sa.Column('target_language', sa.Enum('en', 'kh', name='language'), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('original_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('edited_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('edited_by', sa.UUID(), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('cultural_flag', sa.Boolean(), nullable=False),
    sa.Column('cultural_flag_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['edited_by'], ['keepers.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.ForeignKeyConstraint(['transcript_segment_id'], ['transcript_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_segments_story_id'), 'translation_segments', ['story_id'], unique=False)
    op.create_index(op.f('ix_translation_segments_transcript_segment_id'), 'translation_segments', ['transcript_segment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translation_segments_transcript_segment_id'), table_name='translation_segments')
    op.drop_index(op.f('ix_translation_segments_story_id'), table_name='translation_segments')
    op.drop_table('translation_segments')
    op.drop_index(op.f('ix_transcript_segments_story_id'), table_name='transcript_segments')
    op.drop_table('transcript_segments')
    op.drop_index(op.f('ix_title_suggestions_story_id'), table_name='title_suggestions')
    op.drop_table('title_suggestions')
    op.drop_index(op.f('ix_story_tags_story_id'), table_name='story_tags')
    op.drop_table('story_tags')
    op.drop_index(op.f('ix_keeper_locks_story_id'), table_name='keeper_locks')
    op.drop_table('keeper_locks')
    op.drop_index(op.f('ix_deletion_requests_story_id'), table_name='deletion_requests')
    op.drop_index(op.f('ix_deletion_requests_family_id'), table_name='deletion_requests')
    op.drop_table('deletion_requests')
    op.drop_index(op.f('ix_consent_log_story_id'), table_name='consent_log')
    op.drop_index(op.f('ix_consent_log_family_id'), table_name='consent_log')
    op.drop_table('consent_log')
    op.drop_index(op.f('ix_audio_files_story_id'), table_name='audio_files')
    op.drop_index(op.f('ix_audio_files_family_id'), table_name='audio_files')
    op.drop_table('audio_files')
    op.drop_index(op.f('ix_ai_people_mentions_story_id'), table_name='ai_people_mentions')
    op.drop_table('ai_people_mentions')
    op.drop_index(op.f('ix_stories_family_id'), table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_keepers_family_id'), table_name='keepers')
    op.drop_index(op.f('ix_keepers_email'), table_name='keepers')
    op.drop_table('keepers')
    op.drop_index(op.f('ix_family_members_family_id'), table_name='family_members')
    op.drop_table('family_members')
    op.drop_index(op.f('ix_chapters_family_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_families_slug'), table_name='families')
    op.drop_index(op.f('ix_families_access_token'), table_name='families')
    op.drop_table('families')
    op.drop_table('consent_wording_versions')
    # ### end Alembic commands ###
